# Generated by Django 5.0.6 on 2026-07-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandi',
            name='commodities',
            field=models.ManyToManyField(blank=True, related_name='mandis', to='core.commodity'),
        ),
    ]
