# Generated by Django 5.0.6 on 2026-06-24 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('min_particle_area_px', models.PositiveIntegerField(default=50)),
                ('max_particle_area_px', models.PositiveIntegerField(default=200000)),
                ('expected_min_count', models.PositiveIntegerField(default=20)),
                ('expected_max_count', models.PositiveIntegerField(default=500)),
                ('target_samples', models.PositiveIntegerField(default=500)),
            ],
            options={
                'verbose_name_plural': 'Commodities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mandi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Mandis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submission created'), ('qc_approve', 'QC approved'), ('qc_reject', 'QC rejected'), ('qc_rework', 'Rework requested'), ('label_override', 'Particle label overridden'), ('user_create', 'User created'), ('user_update', 'User updated'), ('export', 'Dataset exported'), ('login', 'User login')], max_length=32)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
