# Generated by Django 5.0.6 on 2026-06-26 10:11

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_superuser_admin_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.GrainUserManager()),
            ],
        ),
    ]
