# Generated by Django 5.0.6 on 2026-06-24 18:43

import annotation.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_number', models.PositiveIntegerField(help_text='Sequential per assayer/session')),
                ('status', models.CharField(choices=[('pending_qc', 'Pending QC'), ('qc_approved', 'QC Approved'), ('qc_rejected', 'QC Rejected'), ('rework_requested', 'Rework Requested')], default='pending_qc', max_length=20)),
                ('total_weight_g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)])),
                ('foreign_matter_g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)])),
                ('fungal_grains_g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)])),
                ('immature_grains_g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)])),
                ('organic_matter_g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)])),
                ('raw_image', models.ImageField(blank=True, null=True, upload_to=annotation.models.submission_raw_path)),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to=annotation.models.submission_crop_path)),
                ('capture_mode', models.CharField(choices=[('auto_capture', 'Auto-capture'), ('manual', 'Manual (not pipeline-eligible)')], default='auto_capture', max_length=16)),
                ('exif_json', models.JSONField(blank=True, default=dict)),
                ('capture_quality_scores', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('qc_notes', models.TextField(blank=True)),
                ('rework_instructions', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assayer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.commodity')),
                ('mandi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mandi')),
                ('qc_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Particle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particle_id', models.PositiveIntegerField(help_text='Index within the submission')),
                ('label', models.CharField(choices=[('good', 'Good grain'), ('broken', 'Broken grain'), ('foreign', 'Foreign particle'), ('immature', 'Immature grain'), ('fungal', 'Fungal / infected'), ('unlabeled', 'Unlabeled')], default='unlabeled', max_length=16)),
                ('polygon', models.JSONField(help_text='List of [x, y] image-space vertices')),
                ('origin', models.CharField(choices=[('auto', 'Auto-detected'), ('user', 'User-added')], default='auto', max_length=8)),
                ('boundary_edited', models.BooleanField(default=False)),
                ('uncertain', models.BooleanField(default=False)),
                ('flagged_by_seg', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('qc_label_override', models.CharField(blank=True, choices=[('good', 'Good grain'), ('broken', 'Broken grain'), ('foreign', 'Foreign particle'), ('immature', 'Immature grain'), ('fungal', 'Fungal / infected'), ('unlabeled', 'Unlabeled')], max_length=16, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('qc_overrider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='particle_overrides', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particles', to='annotation.submission')),
            ],
            options={
                'ordering': ['particle_id'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'created_at'], name='annotation__status_a099ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='particle',
            unique_together={('submission', 'particle_id')},
        ),
    ]
