# Generated by Django 5.0.6 on 2026-06-26 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='measurements_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='foreign_matter_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='fungal_grains_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='immature_grains_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='organic_matter_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_qc', 'Pending QC'), ('qc_approved', 'QC Approved'), ('qc_rejected', 'QC Rejected'), ('rework_requested', 'Rework Requested')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='total_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)]),
        ),
    ]
